// (C) 2018 ERAL
// Distributed under the Boost Software License, Version 1.0.
// (See copy at http://www.boost.org/LICENSE_1_0.txt)

namespace AssetBundleShosha.Editor.Internal {

	public class AssetBundleCryptoKeyTemplate {
		#region Internal const fields

		internal const string kCryptoKeyTemplate = 
@"// This source code was generated by AssetBundleShosha

namespace AssetBundleShoshaUserData {
	using System.Text;
	using System.Linq;
	using System.Security.Cryptography;

	public static class UserData {
		[AssetBundleShosha.AssetBundleCryptoKey(1)]
		private static byte[] AssetBundleCryptoKey {get{
			using (var hash = new SHA1CryptoServiceProvider()) {
				hash.Initialize();
				return hash.ComputeHash(Encoding.UTF8.GetBytes(AssetBundleCryptoPassword)).Take(16).ToArray();
			}
		}}

		private static string AssetBundleCryptoPassword {get{
			//Input Your Password!
			return @""{0}"";
		}}
	}
}
";

		#endregion
	}
}
